PLUS_SIGN = "+"
MINUS_SIGN = '-'
LT_COMPARATOR = '<'
GT_COMPARATOR = '>'
COMMA = ','
DOT = '.'
OPEN_BRACKET = '['
CLOSE_BRACKET = ']'

GRAMMAR = PLUS_SIGN + MINUS_SIGN + LT_COMPARATOR + GT_COMPARATOR + COMMA + DOT + OPEN_BRACKET + CLOSE_BRACKET
